cloud run 1

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,52 +1,65 @@
-# Frontend Dockerfile
-FROM node:18-alpine
+# Dockerfile from: https://github.com/vercel/next.js/tree/canary/examples/with-docker
+FROM node:21-alpine AS base
 
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Copy package.json and package-lock.json
-COPY package*.json ./
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Install dependencies
-RUN npm ci
-
-# Copy the rest of the application code, including next.config.mjs
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# Expose the port the app runs on
+# Comment the following line to enable telemetry data collection (https://nextjs.org/telemetry)
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Comment the following line to enable telemetry data collection
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-# Start the application in development mode
-CMD ["npm", "run", "dev"]
+ENV PORT 3000
 
-
-
-# # This dockerfile is for prodcution
-# # Use an official Node runtime as the parent image
-# FROM node:18-alpine
-
-# # Set the working directory in the container
-# WORKDIR /app
-
-# # Copy package.json and package-lock.json
-# COPY package*.json ./
-
-# # Install dependencies
-# RUN npm ci
-
-# # Copy the rest of the application code
-# COPY . .
-
-# # Build the Next.js application
-# RUN npm run build
-
-# # Expose the port the app runs on
-# EXPOSE 3000
-
-# # Create a script to update environment variables at runtime and start the app
-# RUN echo "#!/bin/sh" > /app/start.sh && \
-#     echo "echo \"NEXT_PUBLIC_API_URL=\$API_URL\" > /app/.env.local" >> /app/start.sh && \
-#     echo "npm start" >> /app/start.sh && \
-#     chmod +x /app/start.sh
-
-# # Start the application
-# CMD ["/app/start.sh"]
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+CMD HOSTNAME="0.0.0.0" node server.js
